### ISSUE TITLE
Flooded console

### ISSUE THREAD

**Issue by Link0Darck** [kennytv/Maintenance#106]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**

When someone refreshes the Minecraft server list it floods me in my console.

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**

https://pastebin.com/HqipLdRy

Or

```
[17:57:41] [Netty IO Thread #3/WARN]: Event ProxyPingEvent(connection=[/192.168.20.249:44380] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=Maintenance, protocol=1), players=ServerPing.Players(max=1000, online=1, sample=null), description=⚠ En cours de maintenance ⚠
⚠ En cours de maintenance ⚠
§x⚠ En cours de maintenance ⚠
§x§F⚠ En cours de maintenance ⚠
§x§F§B⚠ En cours de maintenance ⚠
§x§F§B§F⚠ En cours de maintenance ⚠
§x§F§B§F§F⚠ En cours de maintenance ⚠
§x§F§B§F§F§CNN§xN§x§F§F§F§F§F§F§Coo§xo§x§E§F§F§F§F§F§Cuu§xu§x§Du§x§D§Eu§x§D§E§Fu§x§D§E§F§Fu§x§D§E§F§F§Cu§x§D§E§F§F§C§Asu§x§D§E§F§F§C§As§xu§x§D§E§F§F§C§As§x§D§F§F§F§F§F§C§F§F§C§C §F§F§C§C §x§F§F§C§C §x§C§F§F§C§C §x§C§A§F§F§C§C §x§C§A§F§F§F§C§C §x§C§A§F§F§F§F§C§C §x§C§A§F§F§C§F§F§C§C §x§C§A§F§F§C§Fr§F§F§C§C §x§C§A§F§F§C§Fr§x§F§F§C§C §x§C§A§F§F§C§Fr§x§C§F§F§F§F§F§Dee§xe§x§B§F§F§F§F§F§Dvv§xv§x§Av§x§A§Cv§x§A§C§Fv§x§A§C§F§Fv§x§A§C§F§F§Dii§xi§x§A§F§F§F§F§F§Dee§x§F§F§F§F§F§D§F§F§D§Bn§F§F§D§Bn§x§F§F§F§F§F§F§F§F§F§D§F§F§F§D§Ed§F§F§F§D§Ed§x§F§F§F§F§F§Err§x§B§B§F§B§F§F§B§F§F§Eoo§x§F§F§F§F§F§Enn§x§F§F§F§F§F§Ess§x§E§E§F§E§F§F§E§F§F§E§E§F§F§E§B §E§F§F§E§B §x§F§F§F§F§F§E§F§F§E§Db§F§F§E§Db§x§A§A§F§A§F§F§A§F§F§Fii§x§F§F§F§F§F§Fee§x§F§F§F§F§F§Fnn§x§D§D§F§D§F§F§D§F§F§Ftt§x§F§F§F§F§F§F§F§F§F§Aô§F§F§F§Aô§x§F§F§F§F§F§F§F§F§F§Ct§F§F§F§Ct§x§F§F§F§F§F§F§F§F§F§F§F§F§F§F§F!, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) took 887ms to process!
```

## Server information
**Type '/maintenance dump' and paste the given link here**

```
[03:08:10 INFO]: [MaintenanceBungee] The dump is being created, this might take a moment.
[03:08:10 WARN]: [Maintenance] Could not paste dump :(
[03:08:10 WARN]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hastebin.com/documents
[03:08:10 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[03:08:10 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[03:08:10 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[03:08:10 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[03:08:10 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2051)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2046)
[03:08:10 WARN]:        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2045)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[03:08:10 WARN]:        at eu.kennytv.maintenance.core.MaintenancePlugin.pasteDump(MaintenancePlugin.java:297)
[03:08:10 WARN]:        at eu.kennytv.maintenance.core.command.subcommand.DumpCommand.lambda$execute$0(DumpCommand.java:44)
[03:08:10 WARN]:        at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
[03:08:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[03:08:10 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[03:08:10 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[03:08:10 WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hastebin.com/documents
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[03:08:10 WARN]:        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
[03:08:10 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
[03:08:10 WARN]:        at eu.kennytv.maintenance.core.MaintenancePlugin.pasteDump(MaintenancePlugin.java:292)
[03:08:10 WARN]:        ... 5 more
```

i download ( Maintenance-4.1.0.jar )

**Comment by Link0Darck** [comment]
again with Maintenance-4.2.0.jar

**Comment by Link0Darck** [comment]
again with Maintenance-4.2.1.jar It's been a year and the problem is still not resolved...

**Comment by shooutz** [comment]
try disable ``log-pings`` in bungee config

**Comment by Link0Darck** [comment]
> try disable `log-pings` in bungee config

it is already disabled: log_pings: false

**Comment by Link0Darck** [comment]
the problem comes from: `enable-pingmessages` so this is a plugin problem

**Comment by CodeByCam** [comment]
> the problem comes from: `enable-pingmessages` so this is a plugin problem

Hi there! ^_^
Can you please provide a copy of your configuration file in the form of a [paste link](https://paste.gg/).

**Comment by Link0Darck** [comment]
> > the problem comes from: `enable-pingmessages` so this is a plugin problem
> 
> Hi there! ^_^ Can you please provide a copy of your configuration file in the form of a [paste link](https://paste.gg/).

https://paste.gg/p/anonymous/bd571945ac994d9f9b6b76c560796ef1

**Comment by kennytv** [comment]
Problem is that Bungee warns if an event takes slightly longer than expected, and I'm making the database calls during the ping as opposed to in the background every interval to reduce the total number of queries, but I suppose moving it into the background and always doing it in the configured interval would be better. In the meantime, any logging filter config/plugin to just hide that will work fine

**Comment by Link0Darck** [comment]
> Problem is that Bungee warns if an event takes slightly longer than expected, and I'm making the database calls during the ping as opposed to in the background every interval to reduce the total number of queries, but I suppose moving it into the background and always doing it in the configured interval would be better. In the meantime, any logging filter config/plugin to just hide that will work fine

Good morning,
yes if you have a way to hide it you can do it or make an option if you want to hide it or not thank you in advance

**Comment by kennytv** [comment]
https://hangar.papermc.io/4drian3d/LogFilter

**Comment by Link0Darck** [comment]
> https://hangar.papermc.io/4drian3d/LogFilter

je suis obligé d'utiliser ça ?

**Comment by CodeByCam** [comment]
> > [hangar.papermc.io/4drian3d/LogFilter](https://hangar.papermc.io/4drian3d/LogFilter)
> 
> je suis obligé d'utiliser ça ?

Hi there ^_^
Kenny only speaks German or Australian. Not French.

**Comment by Link0Darck** [comment]
excuse me, I wasn't paying attention, do I have to use that?

**Comment by CodeByCam** [comment]
> excuse me, I wasn't paying attention, do I have to use that?

Hi there! ^_^
No problemo at all! You're excused. You don't _have_ to use that, however it's your best option right now until kenny gets around to fixing this "issue". It will hide that spam from your console.
