### ISSUE TITLE
Unshades slf4j package - incompatibility to certain plugins

### ISSUE THREAD

**Issue by KennyTV** [KennyTV/Maintenance#11]
## Issue
As the slf4j part of the HikariCP dependency, can't be shaded without any extra work (because of self reflection) some (?) plugins also including it will make BungeeCord confuse both classpaths and throw this error:
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of net/md_5/bungee/api/plugin/PluginClassloader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
    at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:418)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
```

**Comment by KennyTV** [comment]
... should be dealt with by bigger plugins creating this problem to be honest
