### ISSUE TITLE
Couldn't pass ProxyInitializeEvent to maintenance 4.2.1

### ISSUE THREAD

**Issue by SrBedrock** [kennytv/Maintenance#126]
## Bug reproducibility
Error on console.

## Error
https://pastebin.com/raw/nVNcx5B0

## Server information
https://pastebin.com/raw/etwg8Jxf

**Comment by jAvEE-fr** [comment]
same here, from latest velocity update

**Comment by SrBedrock** [comment]
```
[09:40:27 INFO] [maintenance]: Updating config to the latest version...
[09:40:27 INFO] [maintenance]: Done! Updated config!
[09:40:27 INFO] [maintenance]: Updating language file to the latest version...
[09:40:27 ERROR]: Couldn't pass ProxyInitializeEvent to maintenance 4.3.0
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.base/java.nio.file.Files.copy(Files.java:3108) ~[?:?]
        at eu.kennytv.maintenance.core.Settings.createFile(Settings.java:143) ~[?:?]
        at eu.kennytv.maintenance.core.Settings.updateLanguageFile(Settings.java:337) ~[?:?]
        at eu.kennytv.maintenance.core.Settings.reloadConfigs(Settings.java:116) ~[?:?]
        at eu.kennytv.maintenance.core.Settings.<init>(Settings.java:90) ~[?:?]
        at eu.kennytv.maintenance.core.proxy.SettingsProxy.<init>(SettingsProxy.java:57) ~[?:?]
        at eu.kennytv.maintenance.velocity.MaintenanceVelocityPlugin.onEnable(MaintenanceVelocityPlugin.java:96) ~[?:?]
        at eu.kennytv.maintenance.velocity.Lmbda$38.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[server.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by MrEisbear** [comment]
https://api.mclo.gs/1/raw/TmZz04p

Experiencing same/similar error with Maintenance 4.3.0 on Velocity 3.4
