### ISSUE TITLE
Doesn't work with KettingPowered?

### ISSUE THREAD

**Issue by AqueleHaru** [kennytv/Maintenance#136]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**
Try to use it with KettingPowered. (1.20.1)

## Error
**Is there an error? Save it via https://mclo.gs/ and link paste the link.**
No. it's just doesnt change the MOTD.

## Server information
**Type '/maintenance dump' and paste the given link here**

 [MaintenanceSpigot] The dump is being created, this might take a moment.
[13:01:39] [Craft Scheduler Thread - 6/WARN] [eu.ke.ma.sp.MaintenanceSpigotBase/]: [Maintenance] Could not paste dump :(
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hastebin.com/documents
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2055)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2050)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2049)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1619)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at eu.kennytv.maintenance.core.MaintenancePlugin.pasteDump(MaintenancePlugin.java:299)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at eu.kennytv.maintenance.core.command.subcommand.DumpCommand.lambda$execute$0(DumpCommand.java:44)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at TRANSFORMER/forge@47.3.6-0.3.25/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at TRANSFORMER/forge@47.3.6-0.3.25/org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]: Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://hastebin.com/documents
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:307)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       at eu.kennytv.maintenance.core.MaintenancePlugin.pasteDump(MaintenancePlugin.java:294)
[13:01:39] [Craft Scheduler Thread - 6/WARN] [/]:       ... 6 more

**Comment by kennytv** [comment]
Hybrid servers are always a bit of a hack and the issue would likely be on them, that's not something I really want to look into

**Comment by JustRed23** [comment]
Not a hybrid issue, hastebin.com simply requires authorization to paste. Looking through the main branch I can see that the link in this error (hastebin.com) does not match with the current link (api.pastes.dev) which leads me to believe that it's an old version

**Comment by JustRed23** [comment]
Seeing that ketting uses spigot, and looking at the readme where it says 'with limited functionality' I'd say that this simply does not support it

**Comment by JustRed23** [comment]
Good to know, I'll add it to the hybrid specific issue tracker then.

**Comment by SrNadien** [comment]
I use it and it works correctly
