### ISSUE TITLE
Error at bootup!

### ISSUE THREAD

**Issue by Ironic8b498** [KennyTV/Maintenance#43]
Running Bungee 1529 and got this server error at bootup 

`23:53:09 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4351c8c3, id=162, owner=hazae41.minecraft.sudo.bungee.SudoBungeePlugin@551de37d, task=mc-sudo.hazae41.minecraft.kotlin.bungee.Kotlin4Bungee__CoreKt$schedule$1$6@6e4d2b16, delay=0, period=0, running=true) encountered an exception
mc-sudo.kotlin.UninitializedPropertyAccessException: lateinit property task has not been initialized
	at mc-sudo.hazae41.minecraft.kotlin.bungee.Kotlin4Bungee__CoreKt$schedule$1$6.run(Core.kt:55)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23:53:09 [INFO] [Maintenance] Enabled ServerListPlus integration!
23:53:09 [INFO] Enabled plugin Maintenance version 3.0.5 by KennyTV
`

**Comment by KennyTV** [comment]
Not a Maintenance issue `owner=hazae41.minecraft.sudo.bungee.SudoBungeePlugin`
