### ISSUE TITLE
doesn't load on latest waterfall (build 392) AND /maintenance dump doesnt work

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [KennyTV/Maintenance#52]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**
Enabled plugin Maintenance version 3.0.5 by KennyTV
WARN 09:30:48
Exception encountered when loading plugin: MaintenanceAddon
Console 09:30:48
java.lang.NoClassDefFoundError: eu/kennytv/maintenance/api/event/MaintenanceReloadedEvent
at eu.kennytv.maintenance.addon.bungee.MaintenanceBungeeAddon.onEnable(MaintenanceBungeeAddon.java:57) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
Caused by: java.lang.ClassNotFoundException: eu.kennytv.maintenance.api.event.MaintenanceReloadedEvent
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-1.16-392.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:ba0f544:392]
at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
... 5 

## Server information
**Type '/maintenance dump' and paste the given link here**
09:36:31
Could not paste dump :(
ERROR 09:36:31
java.net.ConnectException: Connection timed out: connect
at java.base/java.net.PlainSocketImpl.connect0(Native Method)
at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:609)
at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
at eu.kennytv.maintenance.core.MaintenancePlugin.pasteDump(MaintenancePlugin.java:245)
at eu.kennytv.maintenance.core.command.subcommand.DumpCommand.lambda$execute$0(DumpCommand.java:45)
at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

## Versions: 
MaintenanceAddon: 1.0.4 (1.0.3 has also been tried)
Maintenance: 3.0.5
Bungee: Waterfall (392)

seems to work fine spigot side though on 1.16.5

**Comment by KennyTV** [comment]
Like the capital, bold text on the 1.0.4 pre-release says, the addon depends on Maintenance 3.0.6-SNAPSHOT, you can get the latest one from here: https://github.com/KennyTV/Maintenance/suites/1748194916/artifacts/33219116
