### ISSUE TITLE
BUG MYSQL connect

### ISSUE THREAD

**Issue by Link0Darck** [kennytv/Maintenance#65]
## Bug reproducibility
**How does the problem occur/what are the steps to reproduce it?**

the problem is simple it doesn't want to communicate with mysql and it does the same thing with waterfall

## Error
**Is there an error? Save it via https://pastebin.com/ and link paste the link.**

https://pastebin.com/zR8cWLwT

## Server information
**Type '/maintenance dump' and paste the given link here**

https://hastebin.com/ofuyowixeb

**Comment by mjallen729** [comment]
Dead Pastebin link...

**Comment by Link0Darck** [comment]
`02:09:37 [GRAVE] eu.kennytv.lib.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet successfully received from the server was 38 milliseconds ago.  The last packet sent successfully to the server was 31 milliseconds ago.
02:09:37 [GRAVE]     at eu.kennytv.lib.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589)
02:09:37 [GRAVE]     at eu.kennytv.lib.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575)
02:09:37 [GRAVE]     at eu.kennytv.lib.hikari.pool.HikariPool.<init>(HikariPool.java:115)
02:09:37 [GRAVE]     at eu.kennytv.lib.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.proxy.mysql.MySQL.<init>(MySQL.java:53)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.proxy.SettingsProxy.setupMySQL(SettingsProxy.java:69)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.proxy.SettingsProxy.loadExtraSettings(SettingsProxy.java:86)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.Settings.loadSettings(Settings.java:208)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.Settings.reloadConfigs(Settings.java:92)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.Settings.<init>(Settings.java:77)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.core.proxy.SettingsProxy.<init>(SettingsProxy.java:51)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.bungee.MaintenanceBungeePlugin.<init>(MaintenanceBungeePlugin.java:75)
02:09:37 [GRAVE]     at eu.kennytv.maintenance.bungee.MaintenanceBungeeBase.onEnable(MaintenanceBungeeBase.java:32)
02:09:37 [GRAVE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
02:09:37 [GRAVE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
02:09:37 [GRAVE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
02:09:37 [GRAVE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
02:09:37 [GRAVE] Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
`

**Comment by kennytv** [comment]
Does that still happen if you use a dev build (https://github.com/kennytv/Maintenance/suites/2849987097/artifacts/63623920)? Also, have you made sure host, database, user, and password are all setup correctly?

**Comment by Link0Darck** [comment]
Hello
If I contact you, it's because everything else is correct and the same login and password is used by other plugins that use MYSQL and it works, but I will test what you have sent with the link

**Comment by Link0Darck** [comment]
> Cela se produit-il toujours si vous utilisez une version de développement ( https://github.com/kennytv/Maintenance/suites/2849987097/artifacts/63623920 ) ? De plus, vous êtes-vous assuré que l'hôte, la base de données, l'utilisateur et le mot de passe sont tous correctement configurés ?

Hello
If I contact you, it's because everything else is correct and the same login and password is used by other plugins that use MYSQL and it works, but I will test what you have sent with the link
