### ISSUE TITLE
Maintenance plug-in no longer working on newer version of Paper

### ISSUE THREAD

**Issue by zenety** [kennytv/Maintenance#76]
## Bug reproducibility
Upgrade to latest upstream craftbukkit minecraft server release. https://github.com/PaperMC/Paper/pull/7624
Using build 261 or newer from Paper. https://github.com/PaperMC/Paper/commit/855637f967742784c30559a55e4551f47498cee2

On older builds the plug-in works fine.

## Error

```
[10:34:59 INFO]: [Maintenance] Enabling Maintenance v4.0.0
[10:35:00 ERROR]: Error occurred while enabling Maintenance v4.0.0 (Is it up to date?)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-261]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:184) ~[snakeyaml-1.30.jar:?]
[10:35:00 ERROR]: Error occurred while disabling Maintenance v4.0.0 (Is it up to date?)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
```

When trying to use any maintenance commands you get the following error:
`[10:35:34 WARN]: Unexpected exception while parsing console command "maintenance"`

## Server information
Not able to create a dump because plugin is no longer loading.

**Comment by zenety** [comment]
Remade the server and suddenly works. Maybe some mistake in the config.yml.
